# Generated by Django 2.2.7 on 2019-11-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='post',
        ),
    ]
